# image build to GHCR
name: Image Build
on:
  # publish on releases only, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

jobs:
  docker_publish:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4 # Updated to latest version

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }} # it will be lowercased internally
          github_token: ${{ secrets.GH_TOKEN }}